### ISSUE TITLE
update postgres.js to v3

### ISSUE THREAD

**Issue by paulovieira** [JAForbes/pgmg#16]
Nice and simple migrations utility. Congratulations!

The `postgres` module is now on version 3. It might make sense to update `package.json`:

https://github.com/porsager/postgres/releases

**Comment by JAForbes** [comment]
Hey @paulovieira thank you and great point.

I think I should take this opportunity to add a simple integration suite, then upgrade to v3 as I really just wrote this for myself, but I'm using it in prod and happy for others to take advantage of it too.

I'll keep this open until I migrate to v3

**Comment by JAForbes** [comment]
Closing as this is in the `next` branch and will land soon.

**Comment by paulovieira** [comment]
Looking forward for the new version!
